# -*- coding: utf-8 -*-
"""DFS-8puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjAEO7MuGp5mRBp5mql0mpCDZ8KEcx8_
"""

# 8 Puzzle using IDS (Iterative Deepening Search)

start = (1, 2, 3,
         4, 0, 6,
         7, 5, 8)

goal = (1, 2, 3,
        4, 5, 6,
        7, 8, 0)


def get_neighbors(state):
    neighbors = []
    zero = state.index(0)

    for move in [-3, 3, -1, 1]:
        pos = zero + move

        if 0 <= pos < 9:
            if move == -1 and zero % 3 == 0:
                continue
            if move == 1 and zero % 3 == 2:
                continue

            new = list(state)
            new[zero], new[pos] = new[pos], new[zero]
            neighbors.append(tuple(new))

    return neighbors


def dls(state, goal, limit, path):
    if state == goal:
        return path

    if limit == 0:
        return None

    for neighbor in get_neighbors(state):
        if neighbor not in path:
            result = dls(neighbor, goal, limit - 1, path + [neighbor])

            if result is not None:
                return result

    return None


def ids(start, goal):
    for limit in range(31):
        solution = dls(start, goal, limit, [start])

        if solution is not None:
            return solution

    return None


def display(path):
    if path is None:
        print("Solution not found!")
        return

    print("Least number of moves:", len(path) - 1)

    for step, state in enumerate(path):
        print("\nStep", step)
        for i in range(0, 9, 3):
            print(state[i:i + 3])


solution = ids(start, goal)
display(solution)