# -*- coding: utf-8 -*-
"""Tic-tac-toe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qQXVm2loQCnnImT8wEtnt9aH-zQyeWN
"""

# Human = X
# Computer = O

board = [' '] * 9

def display_board():
    print()
    print(board[0] + " | " + board[1] + " | " + board[2])
    print("--+---+--")
    print(board[3] + " | " + board[4] + " | " + board[5])
    print("--+---+--")
    print(board[6] + " | " + board[7] + " | " + board[8])
    print()

def check_winner():
    winning_positions = [
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),
        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),
        (0, 4, 8),
        (2, 4, 6)
    ]


    for a, b, c in winning_positions:
        if board[a] != ' ' and board[a] == board[b] == board[c]:
            return board[a]

    return None


def is_full():
    return ' ' not in board


def minimax(is_computer_turn):
    winner = check_winner()


    if winner == 'O':
        return 10

    if winner == 'X':
        return -10

    if is_full():
        return 0


    if is_computer_turn:
        best_score = -float('inf')

        for i in range(9):
            if board[i] == ' ':
                board[i] = 'O'

                score = minimax(False)

                board[i] = ' '
                best_score = max(best_score, score)

        return best_score


    else:
        best_score = float('inf')

        for i in range(9):
            if board[i] == ' ':
                board[i] = 'X'

                score = minimax(True)

                board[i] = ' '
                best_score = min(best_score, score)

        return best_score


def find_best_move():
    best_score = -float('inf')
    best_move = -1

    for i in range(9):
        if board[i] == ' ':

            board[i] = 'O'

            score = minimax(False)

            board[i] = ' '

            if score > best_score:
                best_score = score
                best_move = i

    return best_move


def play_game():

    print("TIC-TAC-TOE")
    print("You are X")
    print("Computer is O")

    while True:

        display_board()


        while True:
            try:
                move = int(input("Enter position (1-9): ")) - 1

                if move >= 0 and move < 9 and board[move] == ' ':
                    board[move] = 'X'
                    break

                print("Invalid move. Try again.")

            except ValueError:
                print("Enter a number from 1 to 9.")


        if check_winner() == 'X':
            display_board()
            print("Human wins!")
            break

        if is_full():
            display_board()
            print("Draw!")
            break


        computer_move = find_best_move()
        board[computer_move] = 'O'

        print("Computer chose position:", computer_move + 1)


        if check_winner() == 'O':
            display_board()
            print("Computer wins!")
            break

        if is_full():
            display_board()
            print("Draw!")
            break


play_game()