# -*- coding: utf-8 -*-
"""Vaccum-cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OzBMGSt5iowYAVIlCfuDnWV4E2j7cc4i
"""

# Two rooms: A and B


def vacuum_cleaner(position, room_A, room_B):

    print("Initial State:")
    print("Vacuum Position:", position)
    print("Room A:", room_A)
    print("Room B:", room_B)
    print()

    while room_A == "Dirty" or room_B == "Dirty":


        if position == "A":

            if room_A == "Dirty":
                print("Action: SUCK Room A")
                room_A = "Clean"

            elif room_B == "Dirty":
                print("Action: MOVE RIGHT")
                position = "B"

        elif position == "B":

            if room_B == "Dirty":
                print("Action: SUCK Room B")
                room_B = "Clean"

            elif room_A == "Dirty":
                print("Action: MOVE LEFT")
                position = "A"

    print()
    print("Final State:")
    print("Vacuum Position:", position)
    print("Room A:", room_A)
    print("Room B:", room_B)
    print("Goal achieved: Both rooms are CLEAN.")

vacuum_cleaner(position="A", room_A="Dirty", room_B="Dirty")

vacuum_cleaner(position="B", room_A="Dirty", room_B="Dirty")

vacuum_cleaner(position="A", room_A="Dirty", room_B="Clean")

vacuum_cleaner(position="B", room_A="Clean", room_B="Dirty")

vacuum_cleaner(position="A", room_A="Clean", room_B="Clean")